services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
        VITE_BACKEND_URL: http://localhost:5001
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    user: appuser
    security_opt:
      - no-new-privileges:true

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
    env_file:
      - ./backend/.env
    networks:
      - app-network
    user: appuser
    security_opt:
      - no-new-privileges:true

networks:
  app-network:
    driver: bridge