resources:
  - name: resource-repo
    type: git
    icon: github
    source:
      uri: https://github.com/ONS-Innovation/keh-digital-landscape
      username: ((github_access_token))
      password: x-oauth-basic
      branch: ((branch))

# Define the common terraform task as an anchor
terraform-task: &terraform-task
  task: terraform
  privileged: true
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: hashicorp/terraform
    inputs:
      - name: resource-repo
    params:
      secrets: ((sdp_((env))_digital_landscape_secrets))
      github_access_token: ((github_access_token))
      tag: ((tag))
    run:
      path: sh
      args:
        - -cx
        - |
          echo "DEBUG: Environment is ${env}"
          apk add --no-cache jq curl
          if [[ "${env}" == "prod" ]]; then
            tag=$(curl "https://api.github.com/repos/ONS-Innovation/keh-digital-landscape/releases" | jq -r '.[0].tag_name')
            export tag
          else
            export tag=((tag))
          fi
          chmod u+x ./resource-repo/concourse/scripts/terraform_infra.sh
          ./resource-repo/concourse/scripts/terraform_infra.sh
    timeout: 30m

jobs:
  - name: build-and-push-dev
    public: true
    plan:
      - get: resource-repo
        trigger: true
        timeout: 5m
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: resource-repo
          params:
            aws_account_id: ((aws_account_sdp_dev))
            aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
            secrets: ((sdp_dev_digital_landscape_secrets))
            env: dev
            tag: ((tag))
            repo_name: ((repo_name))
          run:
            path: sh
            args:
              - -cx
              - |
                apk add --no-cache aws-cli podman jq iptables curl
                export repo_name=((repo_name))
                export tag=((tag))
                chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
                chmod u+x ./resource-repo/concourse/scripts/build_image.sh
                source ./resource-repo/concourse/scripts/assume_role.sh
                ./resource-repo/concourse/scripts/build_image.sh
        timeout: 10m
      - <<: *terraform-task
        params:
          github_access_token: ((github_access_token))
          env: dev
          tag: ((tag))
          secrets: ((sdp_dev_digital_landscape_secrets))

  - name: build-and-push-prod
    public: true
    plan:
      - get: resource-repo
        passed: [build-and-push-dev]
        trigger: false # Manual trigger only
        timeout: 5m
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: resource-repo
          params:
            aws_account_id: ((aws_account_sdp_prod))
            aws_role_arn: arn:aws:iam::((aws_account_sdp_prod)):role/sdp-concourse-prod
            secrets: ((sdp_prod_digital_landscape_secrets))
            env: prod
            tag: ((tag))
            repo_name: ((repo_name))
          run:
            path: sh
            args:
              - -cx
              - |
                apk add --no-cache aws-cli podman jq iptables curl
                export repo_name=((repo_name))
                tag=$(curl "https://api.github.com/repos/ONS-Innovation/keh-digital-landscape/releases" | jq -r '.[0].tag_name')
                export tag
                chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
                chmod u+x ./resource-repo/concourse/scripts/build_image.sh
                source ./resource-repo/concourse/scripts/assume_role.sh
                ./resource-repo/concourse/scripts/build_image.sh
        timeout: 10m
      - <<: *terraform-task
        params:
          github_access_token: ((github_access_token))
          env: prod
          tag: ((tag))
          secrets: ((sdp_prod_digital_landscape_secrets))
