resource_types:
  - name: key-value
    type: registry-image
    source:
      repository: gstack/keyval-resource

resources:
  - name: resource-repo
    type: git
    icon: github
    source:
      uri: https://github.com/ONS-Innovation/keh-digital-landscape
      username: ((github_access_token))
      password: x-oauth-basic
      branch: ((branch))
  - name: github-release
    type: github-release
    source:
      owner: ONS-Innovation
      repository: keh-digital-landscape
      access_token: ((github_access_token))
  - name: github-release-tag
    type: key-value

# Define the common terraform task as an anchor
terraform-task: &terraform-task
  task: terraform
  privileged: true
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: hashicorp/terraform
    inputs:
      - name: resource-repo
    params:
      secrets: ((sdp_((env))_digital_landscape_secrets))
      github_access_token: ((github_access_token))
      tag: ((tag))
    run:
      path: sh
      args:
        - -cx
        - |
          echo "DEBUG: Environment is ${env}"
          apk add --no-cache jq curl
          export tag=((tag))
          if [[ "$env" == "prod" && ! "$tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Tag '$tag' is not in semantic versioning format (vX.Y.Z)"
            exit 1
          fi
          chmod u+x ./resource-repo/concourse/scripts/terraform_infra.sh
          ./resource-repo/concourse/scripts/terraform_infra.sh
    timeout: 30m

jobs:

  - name: build-and-push-dev
    public: true
    plan:
      - get: resource-repo
        trigger: true
        timeout: 5m
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: resource-repo
          params:
            aws_account_id: ((aws_account_sdp_dev))
            aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
            secrets: ((sdp_dev_digital_landscape_secrets))
            env: dev
            tag: ((tag))
            repo_name: ((repo_name))
          run:
            path: sh
            args:
              - -cx
              - |
                apk add --no-cache aws-cli podman jq iptables curl
                export repo_name=((repo_name))
                export tag=((tag))
                chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
                chmod u+x ./resource-repo/concourse/scripts/build_image.sh
                source ./resource-repo/concourse/scripts/assume_role.sh
                ./resource-repo/concourse/scripts/build_image.sh
        timeout: 10m
      - <<: *terraform-task
        params:
          github_access_token: ((github_access_token))
          env: dev
          tag: ((tag))
          secrets: ((sdp_dev_digital_landscape_secrets))

  - name: deploy-after-github-release
    public: true
    plan:
      - get: github-release
        trigger: true
      - get: resource-repo
        trigger: false
      - task: deploy-release
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: resource-repo
            - name: github-release
          outputs:
            - name: release-tag-output # Output directory for the tag
          params:
            aws_account_id: ((aws_account_sdp_dev))
            aws_role_arn: arn:aws:iam::((aws_account_sdp_dev)):role/sdp-concourse-dev
            secrets: ((sdp_dev_digital_landscape_secrets))
            env: dev
            tag: github-release/tag # Use the release tag from the resource
            repo_name: ((repo_name))
          run:
            path: sh
            args:
              - -cx
              - |
                apk add --no-cache aws-cli podman jq iptables curl
                export repo_name=((repo_name))
                export tag=$(cat github-release/tag)
                # Write the tag to a file for output
                echo "${tag}" > release-tag-output/tag
                echo "Using tag: ${tag}"
                chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
                chmod u+x ./resource-repo/concourse/scripts/build_image.sh
                source ./resource-repo/concourse/scripts/assume_role.sh
                ./resource-repo/concourse/scripts/build_image.sh
        timeout: 15m
      - put: github-release-tag
        params:
          directory: release-tag-output

  - name: build-and-push-prod
    public: true
    plan:
      - get: resource-repo
        passed: [deploy-after-github-release, build-and-push-dev]
        trigger: false # Manual trigger only
        timeout: 5m
      - get: github-release-tag
        passed: [deploy-after-github-release]
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: hashicorp/terraform
          inputs:
            - name: resource-repo
            - name: github-release-tag
          params:
            aws_account_id: ((aws_account_sdp_prod))
            aws_role_arn: arn:aws:iam::((aws_account_sdp_prod)):role/sdp-concourse-prod
            secrets: ((sdp_prod_digital_landscape_secrets))
            env: prod
            tag: github-release-tag/tag
            repo_name: ((repo_name))
          run:
            path: sh
            args:
              - -cx
              - |
                apk add --no-cache aws-cli podman jq iptables curl
                export repo_name=((repo_name))
                export tag=$(cat github-release-tag/tag)
                echo "Using release tag: ${tag}"
                chmod u+x ./resource-repo/concourse/scripts/assume_role.sh
                chmod u+x ./resource-repo/concourse/scripts/build_image.sh
                source ./resource-repo/concourse/scripts/assume_role.sh
                ./resource-repo/concourse/scripts/build_image.sh
        timeout: 10m
      - <<: *terraform-task
        params:
          github_access_token: ((github_access_token))
          env: prod
          tag: release-tag-output/tag
          secrets: ((sdp_prod_digital_landscape_secrets))
