---
name: CI Testing

on:
  push:
    branches: ['**']
    paths:
      - 'testing/backend/**'
      - 'testing/frontend/**'
  pull_request:
    branches: ['**']
    paths:
      - 'testing/backend/**'
      - 'testing/frontend/**'

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    name: Backend Lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: testing/backend
    strategy:
      matrix:
        python-version: ["3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: testing/backend/req_dev.txt
        
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: make setup-dev

      - name: Run linting
        run: make lint
  ui-frontend-test:
    name: Frontend Tests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: Install dependencies
        run: make install-dev

      - name: Start app in background
        run: make dev-ci &

      - name: Run Playwright tests
        run: cd testing/frontend && make setup && make test-ui
