site_name: Digital Landscape
repo_url: https://github.com/ONS-innovation/keh-digital-landscape
repo_name: Digital Landscape

nav:
  - Home: index.md
  - Pages:
      - Tech Radar: pages/radar/index.md
      - Projects: pages/projects/index.md
      - Statistics: pages/statistics/index.md
      - Review: pages/review/index.md
      - Admin: pages/admin/index.md
      - GitHub Copilot: pages/copilot/index.md
  - Backend:
      - Overview: backend/index.md
      - Services:
          - Cognito Service: backend/services/cognitoService.md
          - S3 Service: backend/services/s3Service.md
          - GitHub Service: backend/services/githubService.md
          - Tech Radar Service: backend/services/techRadarService.md
      - Utilities: backend/utilities.md
  - Contexts:
      - Theme: contexts/themeContext.md
      - Data: contexts/dataContext.md
      - Banner: contexts/banner.md
  - Components:
      - Layout: components/layout/index.md
      - Header:
          - Header: components/header/index.md
          - Help Modal: components/header/helpModal.md
      - Sidebar: components/sidebar/index.md
      - Homepage:
          - Changelog: components/homepage/Changelog.md
          - Recent Banners: components/homepage/RecentBanners.md
      - Info Box: components/infoBox.md
      - Projects:
          - Projects: components/projects/index.md
          - Project Modal: components/projects/projectModal.md
          - Pie Chart: components/projects/pieChart.md
          - Filter Group: components/projects/filterGroup.md
      - MultiSelect: components/multiSelect.md
      - Skeletons: components/skeletons.md
      - Statistics: components/statistics.md
      - Theme Toggle: components/themeToggle.md
      - Admin:
          - Technology Management: components/admin/techManagement.md
          - Banner Management: components/admin/bannerManagement.md
  - Utilities:
    - Technology Status: utilities/technologyStatus.md
    - Tech Radar Data: utilities/techRadarData.md
    - Project Data: utilities/projectData.md
    - Repository Data: utilities/repositoryData.md
    - Custom Fetch: utilities/customFetch.md
  - Constants:
      - Project Constants: constants/projectConstants.md
  - Testing:
      - Overview: testing/index.md
      - Backend: testing/backend.md
      - Accessibility: testing/accessibility.md
  - Additional Notes:
      - Multiple Directorates Support: additionalNotes/directorateSupport.md
  - MkDocs:
      - Documentation: documentation.md
theme:
  name: material
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide

  logo: assets/logo.png
  favicon: assets/favicon.ico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: '..'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js
